from .models import DashboardSummary, DecisionCard, RejectLog
from typing import List

class DashboardRenderer:
    """
    (IS-27) Renders a static HTML page for IssueSignal Dashboard.
    """
    def render(self, summary: DashboardSummary) -> str:
        html = f"""
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>IssueSignal Operator Dashboard</title>
    <style>
        :root {{
            --bg: #F9FAFB;
            --card-bg: #FFFFFF;
            --text-main: #111827;
            --text-sub: #6B7280;
            --emerald: #10B981;
            --blue: #3B82F6;
            --amber: #F59E0B;
            --red: #EF4444;
            --border: #E5E7EB;
        }}
        body {{ font-family: -apple-system, system-ui, sans-serif; background: var(--bg); color: var(--text-main); margin: 0; padding: 20px; }}
        .header {{ display: flex; justify-content: space-between; align-items: center; margin-bottom: 30px; border-bottom: 2px solid var(--border); padding-bottom: 10px; }}
        .status-badge {{ padding: 4px 12px; border-radius: 999px; font-weight: bold; font-size: 0.8em; }}
        .status-success {{ background: #D1FAE5; color: #065F46; }}
        
        .summary-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 15px; margin-bottom: 30px; }}
        .summary-card {{ background: var(--card-bg); padding: 15px; border-radius: 8px; border: 1px solid var(--border); box-shadow: 0 1px 3px rgba(0,0,0,0.1); }}
        .summary-card .count {{ font-size: 1.5em; font-weight: bold; margin-top: 5px; }}
        
        .section-title {{ font-size: 1.25em; font-weight: bold; margin: 30px 0 15px 0; display: flex; align-items: center; gap: 8px; }}
        
        .insight-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 20px; }}
        .decision-card {{ background: var(--card-bg); border-left: 5px solid var(--emerald); padding: 20px; border-radius: 8px; border-top: 1px solid var(--border); border-right: 1px solid var(--border); border-bottom: 1px solid var(--border); box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1); }}
        .decision-card .title {{ font-size: 1.1em; font-weight: bold; margin-bottom: 10px; }}
        .decision-card .metas {{ font-size: 0.85em; color: var(--text-sub); display: flex; flex-wrap: wrap; gap: 10px; margin-bottom: 15px; }}
        .decision-card .meta-item {{ background: #F3F4F6; padding: 2px 8px; border-radius: 4px; }}
        
        .watchlist-table {{ width: 100%; border-collapse: collapse; background: var(--card-bg); border-radius: 8px; overflow: hidden; border: 1px solid var(--border); }}
        .watchlist-table th {{ background: #F3F4F6; text-align: left; padding: 12px; font-size: 0.9em; }}
        .watchlist-table td {{ padding: 12px; border-top: 1px solid var(--border); font-size: 0.9em; }}
        
        .reject-log {{ font-family: monospace; font-size: 0.85em; background: #FFF; border: 1px solid var(--border); padding: 15px; border-radius: 8px; }}
        .reject-item {{ border-bottom: 1px dashed var(--border); padding: 5px 0; }}
        .reject-item:last-child {{ border-bottom: none; }}
        .reject-code {{ color: var(--red); font-weight: bold; }}
    </style>
</head>
<body>
    <div class="header">
        <div>
            <h1 style="margin:0; font-size: 1.5em;">🛡️ IssueSignal Operator</h1>
            <div style="color: var(--text-sub); font-size: 0.9em;">As of {summary.date}</div>
        </div>
        <div class="status-badge status-success">ENGINE: {summary.engine_status}</div>
    </div>

    <div class="summary-grid">
        {self._render_counters(summary.counts)}
    </div>

    <div class="section-title">✨ TOP TRUST_LOCKED INSIGHTS</div>
    <div class="insight-grid">
        {self._render_top_cards(summary.top_cards)}
    </div>

    <div class="section-title">🔭 PRE_TRIGGER WATCHLIST</div>
    <div class="watchlist-section">
        {self._render_watchlist(summary.watchlist)}
    </div>

    <div class="section-title">🚫 SILENT QUEUE & REJECTIONS</div>
    <div class="reject-log">
        {self._render_reject_logs(summary.reject_logs)}
    </div>
    
    <div style="margin-top: 50px; text-align: center; color: var(--text-sub); font-size: 0.8em;">
        Generated by IssueSignal IS-27
    </div>
</body>
</html>
        """
        return html

    def _render_counters(self, counts: dict) -> str:
        items = []
        colors = {
            "TRUST_LOCKED": "#10B981",
            "REJECT": "#EF4444",
            "PRE_TRIGGER": "#3B82F6",
            "HOLD": "#F59E0B"
        }
        for status, count in counts.items():
            color = colors.get(status, "#6B7280")
            items.append(f"""
            <div class="summary-card" style="border-top: 3px solid {color}">
                <div style="font-size: 0.8em; color: var(--text-sub);">{status}</div>
                <div class="count">{count}</div>
            </div>
            """)
        return "\n".join(items)

    def _render_top_cards(self, cards: List[DecisionCard]) -> str:
        if not cards: return "<div style='color:var(--text-sub)'>No high-trust insights available today.</div>"
        items = []
        for c in cards:
            items.append(f"""
            <div class="decision-card">
                <div class="title">{c.title}</div>
                <div class="metas">
                    <span class="meta-item">WHO: {c.actor}</span>
                    <span class="meta-item">TYPE: {c.trigger_type}</span>
                    <span class="meta-item">ITEM: {c.must_item}</span>
                </div>
                <div style="font-size: 0.95em; line-height: 1.5; margin-bottom: 15px;">
                    {c.one_liner}
                </div>
                <div style="font-size: 0.85em; border-top: 1px solid var(--border); padding-top: 10px;">
                    <span style="color: var(--red); font-weight: bold;">KILL_SWITCH:</span> {c.kill_switch}
                </div>
                <div style="font-size: 0.7em; margin-top: 10px; color: var(--text-sub);">SIG: {c.signature or '-'}</div>
            </div>
            """)
        return "\n".join(items)

    def _render_watchlist(self, cards: List[DecisionCard]) -> str:
        if not cards: return "<div style='color:var(--text-sub)'>Watchlist empty.</div>"
        rows = []
        for c in cards:
            rows.append(f"""
            <tr>
                <td><b>{c.title}</b></td>
                <td>{c.actor}</td>
                <td>{c.trigger_type}</td>
                <td style="color: var(--blue)">PRE_TRIGGER</td>
            </tr>
            """)
        return f"""
        <table class="watchlist-table">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Actor</th>
                    <th>Type</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                {''.join(rows)}
            </tbody>
        </table>
        """

    def _render_reject_logs(self, logs: List[RejectLog]) -> str:
        if not logs: return "No rejections logged recently."
        items = []
        for l in logs:
            items.append(f"""
            <div class="reject-item">
                [{l.timestamp}] <span class="reject-code">{l.reason_code}</span> | 
                <b>{l.topic_id}</b>: {l.fact_text}
            </div>
            """)
        return "\n".join(items)
