#!/bin/bash

# Project HOIN Git Push Helper

REPO_URL="https://github.com/darklth/hoininsight_project.git"
COMMIT_MSG="Initial content generated by HOIN Agent: System Config, Script 001, and README"

echo "Checking for Git installation..."
if ! command -v git &> /dev/null; then
    echo "Error: Git is not installed. Please install Xcode Command Line Tools or Git manually."
    exit 1
fi

echo "Initializing Git repository..."
if [ ! -d ".git" ]; then
    git init
    echo "Git initialized."
fi

echo "Configuring remote..."
if git remote | grep -q "origin"; then
    git remote set-url origin "$REPO_URL"
else
    git remote add origin "$REPO_URL"
fi

echo "Adding files..."
git add .

echo "Committing..."
git commit -m "$COMMIT_MSG"

echo "Pushing to main..."
git branch -M main
git push -u origin main

echo "Done! Project HOIN files have been pushed to $REPO_URL"
