
import json
from pathlib import Path
from typing import Dict, List, Optional

class ContentEngine:
    """[TASK #090] CONTENT GENERATION ENGINE
    엔진 결과를 '경제사냥꾼형 콘텐츠'로 변환
    """
    
    def __init__(self):
        from src.core.gemini_client import GeminiClient
        self.gemini = GeminiClient()
        
    def generate_contents(self, fact_pack: List[Dict]) -> List[Dict]:
        all_contents = []
        
        for cand in fact_pack:
            classification = cand.get("classification", "NORMAL")
            
            # 1. Scenario Selection (Decision Engine)
            selected_scenario, confidence = self._select_best_scenario(cand.get("scenarios", []))
            
            # 2. Theme & Stock Mapping
            mapping = self._map_themes_and_stocks(cand)
            
            # 3. Action Determination
            action = self._determine_action(classification, cand)
            
            # 4. Script Generation (Dual Mode)
            script = self._generate_script(cand, classification, selected_scenario)
            
            if script:
                content_res = {
                    "content_type": classification,
                    "topic": cand["topic"],
                    "script": script,
                    "selected_scenario": selected_scenario,
                    "confidence": confidence,
                    "themes": mapping.get("themes", []),
                    "stocks": mapping.get("stocks", []),
                    "action": action
                }
                all_contents.append(content_res)
            
        return all_contents

    def _select_best_scenario(self, scenarios: List[Dict]) -> (str, float):
        """3개 시나리오 중 가장 유력한 것 선택 (Mock logic for now, can use LLM ranking)"""
        if not scenarios:
            return "정보 부족으로 인한 중립 시나리오", 0.5
        
        # Simple heuristic: The first one is often the most 'Normal' or 'Primary' if generated by LLM
        # In a real scenario, we'd rank them by fact alignment.
        top = scenarios[0]
        return top.get("scenario", "기본 시나리오"), 0.65

    def _map_themes_and_stocks(self, candidate: Dict) -> Dict:
        """이벤트 및 증거 꾸러미에서 테마와 종목 정보를 추출 (데이터 기반 동적 추출)"""
        mapping = {"themes": [], "stocks": []}
        
        # 1. candidate 자체에 포함된 themes/stocks 사용 (TopicSelectionEngine에서 생성한 경우)
        mapping["themes"].extend(candidate.get("themes", []))
        mapping["stocks"].extend(candidate.get("stocks", []))
        
        # 2. evidence_bundle에서 키워드 추출 (간이 로직)
        evidence = candidate.get("evidence_bundle", {})
        for event in evidence.get("related_events", []):
            # [HUNTER DNA] 이벤트 텍스트 내에서 []로 표시된 키워드나 명사 위주 추출 (향후 LLM 강화 가능)
            if "[" in event and "]" in event:
                tag = event.split("[")[1].split("]")[0]
                if tag not in ["NEWS", "DART", "DEEP_DETAIL"]:
                    mapping["themes"].append(tag)
        
        # Deduplicate
        mapping["themes"] = list(set(mapping["themes"]))
        
        seen_stocks = set()
        unique_stocks = []
        for s in mapping["stocks"]:
            s_name = s.get("name")
            if s_name not in seen_stocks:
                unique_stocks.append(s)
                seen_stocks.add(s_name)
        mapping["stocks"] = unique_stocks
        
        return mapping

    def _determine_action(self, classification: str, candidate: Dict) -> str:
        if classification == "ANOMALY":
            # Check strength
            strength = candidate.get("strength", 5.0)
            return "OPPORTUNITY" if strength > 7.0 else "RISK"
        else:
            return "WATCH" if candidate.get("strength", 5.0) > 6.0 else "WAIT"

    def generate_visual_assets(self, candidate: Dict, topic_dir: Path) -> bool:
        """[v24.0] 주제에 맞는 커버 이미지 및 에셋 생성"""
        topic = candidate.get("topic", "N/A")
        
        # 1. 커버 이미지 (cover.png) 생성 프롬프트
        # [HUNTER DNA] 하이테크, 사이버네틱, 진지한 금융 분석가 스타일
        cover_prompt = f"A high-tech, cinematic digital art style representing the economic theme: '{topic}'. " \
                       f"Dark blue and metallic silver color palette. Strategic financial symbols, " \
                       f"cybernetic data streams, futuristic city background. Professional, high-fidelity, 8k resolution."
        
        assets_dir = topic_dir / "assets"
        assets_dir.mkdir(parents=True, exist_ok=True)
        
        success = self.gemini.generate_images(cover_prompt, str(assets_dir / "cover.png"))
        
        # 2. 추가 에셋 (배경용) 생성 (옵션)
        if success:
             print(f"  🎨 [CONTENT_ENGINE] Visual assets generated in {assets_dir}")
        return success

    def generate_insta_cards(self, candidate: Dict, script: str = "") -> Optional[List[Dict]]:
        """인스타그램 8단계 카드뉴스 전용 원고 생성 (Resilient Parsing + Script Base)"""
        from src.prompts.insta_prompt import INSTA_PROMPT_TEMPLATE, INSTA_SYSTEM_PROMPT
        import re
        
        evidence = candidate.get("evidence_bundle", {})
        data_chain = evidence.get("data_chain", "N/A")

        # [v23.5] HOIN Insight 지능형 카드뉴스 템플릿 적용
        prompt = INSTA_PROMPT_TEMPLATE.format(
            topic=candidate.get("topic", "N/A"),
            script=script,
            data_chain=json.dumps(data_chain, ensure_ascii=False, indent=2)
        )

        try:
            # [v23.5] 시스템 프롬프트 주입 및 다이렉트 호출
            raw_res = self.gemini.call_controlled(
                prompt, 
                system_prompt=INSTA_SYSTEM_PROMPT,
                agent="INSTA_WRITER", 
                tier=1
            )
            
            # JSON 블록 추출 ({ ... })
            json_match = re.search(r'(\{[\s\S]*\})', raw_res)
            if json_match:
                json_str = json_match.group(1)
                res = json.loads(json_str)
                if "slides" in res:
                    return res["slides"]
            
        except Exception as e:
            print(f"  ⚠️ Insta Card 생성/파싱 실패: {e}")
        return None

    def _generate_script(self, candidate: Dict, classification: str, scenario: str) -> str:
        """LLM을 이용한 경제사냥꾼 스타일 스크립트 작성 (Centralized Prompt DNA)"""
        from src.prompts.writer_prompt import WRITER_PROMPT_TEMPLATE, WRITER_SYSTEM_PROMPT
        
        # 2. 분석 JSON 구성 (WHY Hypothesis 등 포함)
        analysis_data = {
            "why_hypothesis": candidate.get("why_hypothesis", "N/A"),
            "mechanism": candidate.get("mechanism", "N/A"),
            "predictive_chain": candidate.get("predictive_chain", "N/A"),
            "historical_parallel": candidate.get("historical_parallel", "N/A"),
            "confidence": candidate.get("hypothesis_confidence", "N/A"),
            "classification": classification,
            "selected_scenario": scenario,
            "stocks_analysis": candidate.get("stocks_analysis", {})
        }

        # 3. 중앙 집중식 템플릿에 데이터 주입
        evidence = candidate.get("evidence_bundle", {})
        social_intel = evidence.get("social_intelligence", "N/A")
        data_chain = evidence.get("data_chain", "N/A")

        prompt = WRITER_PROMPT_TEMPLATE.format(
            stocks_json=json.dumps(candidate.get("stocks", []), ensure_ascii=False),
            topic=candidate.get("topic", "N/A"),
            data_chain=json.dumps(data_chain, ensure_ascii=False, indent=2),
            social_intelligence=json.dumps(social_intel, ensure_ascii=False, indent=2),
            arbiter_rationale=candidate.get("arbiter_rationale", "N/A"),
            hunter_insight=candidate.get("hunter_insight", "N/A"),
            analysis_json=json.dumps(analysis_data, ensure_ascii=False)
        )
        
        # JSON 응답을 위한 최종 지시사항 추가 (고충실도 리포트 포맷)
        prompt += "\n\n반드시 아래 JSON 형식으로만 응답해라:\n"
        prompt += "{\"title\": \"리포트 제목\", \"script\": \"[본문 내용 (마크다운 형식, 영상 대본 포맷 절대 금지)]\"}"

        try:
            res = self.gemini.call_json_controlled(
                prompt, 
                system_prompt=WRITER_SYSTEM_PROMPT, 
                agent="WRITER", 
                tier=1
            )
            if isinstance(res, dict) and "script" in res:
                return res["script"]
            if isinstance(res, str) and len(res) > 50:
                return res
        except Exception as e:
            print(f"  ⚠️ ContentEngine Gemini 호출 실패: {e}")
            print(f"  💡 [Fallback] 결정론적 템플릿으로 스크립트를 생성합니다.")
            
            # [DETERMINISTIC FALLBACK SCRIPT]
            fallback_script = f"""# [ECONOMIC HUNTER] {candidate.get('topic', 'N/A')}

[HOOK]
데이터가 가리키는 오늘의 핵심 징후는 '{candidate.get('topic')}'입니다. 시장이 표면적인 뉴스에 매몰되어 있을 때, 사냥꾼은 그 이면의 숫자를 봅니다.

[CONTEXT]
{candidate.get('arbiter_rationale', '현재 시장 데이터에서 특이점이 포착되었습니다.')}

[HUNTER'S INSIGHT]
{candidate.get('hunter_insight', '인과관계의 끝단을 추적한 결과, 특정 자산군으로의 수급 쏠림이 예상됩니다.')}

[DATA CHAIN]
{candidate.get('data_chain', 'DART 및 소셜 트렌드 지표가 상호 검증되었습니다.')}

[ACTION]
지금은 대중의 투매나 흥분을 따라갈 때가 아닙니다. 위에서 언급된 핵심 인과관계를 중심으로 포트폴리오의 리스크를 재점검하고, 다음 자금의 길목을 선점하십시오.
"""
            return fallback_script

        return None

    def _build_normal_prompt(self, cand: Dict, scenario: str) -> str:
        return f"""
        당신은 금융권의 '경제사냥꾼' 뉴스 앵커입니다. 다음 데이터를 바탕으로 시청자를 매료시킬 스크립트를 작성하세요.
        단순한 사실 관계 나열이 아닌, 질문을 던지고 맥락을 이해시키는 것이 목적입니다.
        
        [데이터 요약]
        토픽: {cand['topic']}
        정상 흐름: {json.dumps(cand.get('normal_flow', {}), ensure_ascii=False)}
        선택된 시나리오: {scenario}
        핵심 수치: {json.dumps(cand.get('core_facts', []), ensure_ascii=False)}
        
        [스크립트 구조]
        1단계: Hook (시장의 이상한 점에 대한 도발적 질문)
        2단계: Normal Flow 설명 (본래라면 어떻게 움직여야 하는가)
        3단계: Scenario 설명 (우리가 고려해야 할 3가지 시나리오의 핵심)
        4단계: 현재 가장 유율한 해석 (데이터 기반의 결론)
        5단계: Implication (테마 및 종목 연결)
        6단계: Action (시청자에게 주는 명확한 행동 지침: WATCH/WAIT 등)
        
        반드시 JSON 형식으로 응답하세요: {{"script": "태그 없이 작성된 전체 스크립트 텍스트"}}
        """

    def _build_anomaly_prompt(self, cand: Dict, scenario: str) -> str:
        return f"""
        당신은 시장의 모순을 사냥하는 '경제사냥꾼'입니다. 현재 포착된 '비정상적 괴리(ANOMALY)'를 바탕으로 날카로운 분석 스크립트를 작성하세요.
        상황의 긴박함과 매매 기회를 포착하는 느낌을 살리세요.
        
        [데이터 요약]
        토픽: {cand['topic']}
        예상(Expected): {json.dumps(cand.get('anomaly_overlay', {}).get('expected', {}), ensure_ascii=False)}
        실제(Reality): {json.dumps(cand.get('anomaly_overlay', {}).get('actual', {}), ensure_ascii=False)}
        불일치 지점: {cand.get('anomaly_overlay', {}).get('mismatch', [])}
        WHY NOW: {cand.get('why_now', [])}
        
        [스크립트 구조]
        1단계: Hook (시장의 모순을 직설적으로 제시)
        2단계: Expected (정상적인 시장이라면 이래야 했다)
        3단계: Reality (현실은 이렇다 - 수치 기반)
        4단계: Mismatch (왜 괴리가 발생하는가 - 세력의 의도나 숨겨진 변수)
        5단계: WHY NOW (지금 이 분석이 왜 중요한가)
        6단계: Implication (어떤 기회나 리스크가 있는가)
        7단계: Action (명확한 투자 지침: OPPORTUNITY/RISK)
        
        반드시 JSON 형식으로 응답하세요: {{"script": "태그 없이 작성된 전체 스크립트 텍스트"}}
        """
