
import json
from pathlib import Path
from typing import Dict, List, Optional

class ContentEngine:
    """[TASK #090] CONTENT GENERATION ENGINE
    엔진 결과를 '경제사냥꾼형 콘텐츠'로 변환
    """
    
    def __init__(self):
        from src.core.gemini_client import GeminiClient
        self.gemini = GeminiClient()
        
    def generate_contents(self, fact_pack: List[Dict]) -> List[Dict]:
        all_contents = []
        
        for cand in fact_pack:
            classification = cand.get("classification", "NORMAL")
            
            # 1. Scenario Selection (Decision Engine)
            selected_scenario, confidence = self._select_best_scenario(cand.get("scenarios", []))
            
            # 2. Theme & Stock Mapping
            mapping = self._map_themes_and_stocks(cand)
            
            # 3. Action Determination
            action = self._determine_action(classification, cand)
            
            # 4. Script Generation (Dual Mode)
            script = self._generate_script(cand, classification, selected_scenario)
            
            content_res = {
                "type": classification,
                "title": cand["topic"],
                "script": script,
                "selected_scenario": selected_scenario,
                "confidence": confidence,
                "themes": mapping.get("themes", []),
                "stocks": mapping.get("stocks", []),
                "action": action
            }
            all_contents.append(content_res)
            
        return all_contents

    def _select_best_scenario(self, scenarios: List[Dict]) -> (str, float):
        """3개 시나리오 중 가장 유력한 것 선택 (Mock logic for now, can use LLM ranking)"""
        if not scenarios:
            return "정보 부족으로 인한 중립 시나리오", 0.5
        
        # Simple heuristic: The first one is often the most 'Normal' or 'Primary' if generated by LLM
        # In a real scenario, we'd rank them by fact alignment.
        top = scenarios[0]
        return top.get("scenario", "기본 시나리오"), 0.65

    def _map_themes_and_stocks(self, candidate: Dict) -> Dict:
        """이벤트 -> 섹터 -> 테마 -> 종목 연결"""
        topic = candidate["topic"].lower()
        mapping = {"themes": [], "stocks": []}
        
        # Rule-based mapping (Expandable)
        rules = {
            "유가": {"themes": ["정유", "에너지", "신재생"], "stocks": ["S-Oil", "SK이노베이션"]},
            "휴전": {"themes": ["방산", "에너지", "재건"], "stocks": ["한화에어로스페이스", "현대로템"]},
            "삼성": {"themes": ["반도체", "HBM"], "stocks": ["삼성전자", "SK하이닉스"]},
            "금리": {"themes": ["금융", "기술주", "성장주"], "stocks": ["KB금융", "NAVER"]},
            "달러": {"themes": ["수출주", "여행", "항공"], "stocks": ["현대차", "대한항공"]},
            "deepseek": {"themes": ["AI", "반도체소부장"], "stocks": ["한미반도체", "리노공업"]}
        }
        
        for key, val in rules.items():
            if key in topic:
                mapping["themes"].extend(val["themes"])
                mapping["stocks"].extend(val["stocks"])
        
        # Deduplicate
        mapping["themes"] = list(set(mapping["themes"]))
        mapping["stocks"] = list(set(mapping["stocks"]))
        
        return mapping

    def _determine_action(self, classification: str, candidate: Dict) -> str:
        if classification == "ANOMALY":
            # Check strength
            strength = candidate.get("strength", 5.0)
            return "OPPORTUNITY" if strength > 7.0 else "RISK"
        else:
            return "WATCH" if candidate.get("strength", 5.0) > 6.0 else "WAIT"

    def _generate_script(self, candidate: Dict, classification: str, scenario: str) -> str:
        """LLM을 이용한 경제사냥꾼 스타일 스크립트 작성"""
        
        if classification == "ANOMALY":
            prompt = self._build_anomaly_prompt(candidate, scenario)
            fallback = f"""
시장에서 일어날 수 없는 모순이 포착되었습니다.
원래 상황이라면 {json.dumps(candidate.get('anomaly_overlay',{}).get('expected',{}), ensure_ascii=False)} 흐름이 정상입니다.
그런데 현실은 반대로 가고 있습니다. 
이 괴리가 의미하는 것은 명확합니다. 지금 세력은 다른 곳을 보고 있습니다.
우리가 주목해야 할 시나리오는 '{scenario}'입니다.
지금 당장 포지션을 점검하고 {candidate.get('action', '조심')} 하시기 바랍니다.
            """
        else:
            prompt = self._build_normal_prompt(candidate, scenario)
            fallback = f"""
시장에 묘한 흐름이 감지되고 있습니다.
왜 이런 현상이 발생할까요? 원래 정상적인 상황이라면 시장은 특정 방향으로 움직여야 합니다.
하지만 현재 {candidate['topic']} 현상이 나타나고 있죠.
이걸 해석하는 3가지 시나리오 중 특히 '{scenario}' 가능성을 주목해야 합니다.
데이터를 종합해볼 때, 지금은 {candidate.get('action', '관망')}이 필요한 시점입니다.
            """
            
        try:
            res = self.gemini.call_json_controlled(prompt, agent="WRITER", tier=1)
            if isinstance(res, dict) and "script" in res:
                return res["script"]
            if isinstance(res, str) and len(res) > 50:
                return res
        except:
            pass

        return fallback

    def _build_normal_prompt(self, cand: Dict, scenario: str) -> str:
        return f"""
        당신은 금융권의 '경제사냥꾼' 뉴스 앵커입니다. 다음 데이터를 바탕으로 시청자를 매료시킬 스크립트를 작성하세요.
        단순한 사실 관계 나열이 아닌, 질문을 던지고 맥락을 이해시키는 것이 목적입니다.
        
        [데이터 요약]
        토픽: {cand['topic']}
        정상 흐름: {json.dumps(cand.get('normal_flow', {}), ensure_ascii=False)}
        선택된 시나리오: {scenario}
        핵심 수치: {json.dumps(cand.get('core_facts', []), ensure_ascii=False)}
        
        [스크립트 구조]
        1단계: Hook (시장의 이상한 점에 대한 도발적 질문)
        2단계: Normal Flow 설명 (본래라면 어떻게 움직여야 하는가)
        3단계: Scenario 설명 (우리가 고려해야 할 3가지 시나리오의 핵심)
        4단계: 현재 가장 유율한 해석 (데이터 기반의 결론)
        5단계: Implication (테마 및 종목 연결)
        6단계: Action (시청자에게 주는 명확한 행동 지침: WATCH/WAIT 등)
        
        반드시 JSON 형식으로 응답하세요: {{"script": "태그 없이 작성된 전체 스크립트 텍스트"}}
        """

    def _build_anomaly_prompt(self, cand: Dict, scenario: str) -> str:
        return f"""
        당신은 시장의 모순을 사냥하는 '경제사냥꾼'입니다. 현재 포착된 '비정상적 괴리(ANOMALY)'를 바탕으로 날카로운 분석 스크립트를 작성하세요.
        상황의 긴박함과 매매 기회를 포착하는 느낌을 살리세요.
        
        [데이터 요약]
        토픽: {cand['topic']}
        예상(Expected): {json.dumps(cand.get('anomaly_overlay', {}).get('expected', {}), ensure_ascii=False)}
        실제(Reality): {json.dumps(cand.get('anomaly_overlay', {}).get('actual', {}), ensure_ascii=False)}
        불일치 지점: {cand.get('anomaly_overlay', {}).get('mismatch', [])}
        WHY NOW: {cand.get('why_now', [])}
        
        [스크립트 구조]
        1단계: Hook (시장의 모순을 직설적으로 제시)
        2단계: Expected (정상적인 시장이라면 이래야 했다)
        3단계: Reality (현실은 이렇다 - 수치 기반)
        4단계: Mismatch (왜 괴리가 발생하는가 - 세력의 의도나 숨겨진 변수)
        5단계: WHY NOW (지금 이 분석이 왜 중요한가)
        6단계: Implication (어떤 기회나 리스크가 있는가)
        7단계: Action (명확한 투자 지침: OPPORTUNITY/RISK)
        
        반드시 JSON 형식으로 응답하세요: {{"script": "태그 없이 작성된 전체 스크립트 텍스트"}}
        """
